spring.datasource.url=jdbc:postgresql://localhost:5432/transportadora_db
spring.datasource.username=postgres
spring.datasource.password=S@s33235931
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=true