spring.application.name=tcc-backend

# ======= CONFIGURAÇÃO DO BANCO DE DADOS POSTGRESQL =======
spring.datasource.url=jdbc:postgresql://localhost:5432/transportadora_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
